services:
  fyzj-web:
    build: .
    container_name: fyzj-web
    restart: always
    env_file: [ .env ]
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
